version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: bobo_nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/var/www/html
    depends_on:
      - php
      - db
    restart: always

  php:
    build: ./php
    container_name: bobo_php
    volumes:
      - ./www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    restart: always

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: electricity
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
